docker-entrypoint.sh

Included the variable `$LOCAL_CONTRACTS`. If it is equal to "true", it will wait for the file `/usr/local/keeper-contracts/ready` to exists before starting. In other case it will start directly.
Related to Issue oceanprotocol/docker-images#25

New variable to enable waiting for contracts

---

README.md

Added a short note about a little trick to get the Swagger docs to load. I'm not sure why it works, but it does. When I disable insecure localhost, the docs once again won't load.
I also made a few minor copy-edits to the **API documentation** section.
No.

Added note re/ viewing the Swagger docs

---

requirements_conda.txt
requirements_dev.txt

This pull request removes several dependencies from requirements_dev.txt (and _conda.txt):
- Direct requirements for `base58`, `BigchainDB`, `bigchaindb-driver`, `cryptoconditions`, `cryptography`, `pyasn1` and `python-rapidjson` aren't needed, because those should come indirectly through the requirements of `oceandb-bigchaindb-driver`
- The requirement for `oceandb-bigchaindb-driver` was commented-out for now, because it was causing problems: if you [look at the setup.py file for that package](https://github.com/oceanprotocol/oceandb-bigchaindb-driver/blob/3900a665c7a43307181be118fa53e46a9b45784c/setup.py#L14), you'll see that it lists `bigchaindb-driver` and `BigchainDB` as requirements, but since no version is specified for `BigchainDB`, it assumes the latest non-beta, non-alpha …

Get pip install -r requirements_dev.txt working

---

docs/for_aquarius_devs/README.md

- Added help with installing OS-level requirements
- Added a note/reminder to use a virtualenv or equivalent
- Removed the mention of `./scripts/deploy` because that is gone and not needed any more
I didn't edit the docs about Configuration because I gather that's all changing.

Fix & augment the Aquarius docs for devs

---

aquarius/__init__.py
config.ini.template
docs/for_aquarius_devs/README.md

because Aquarius no longer connects to any Ethereum client (such as Ganache) and so doesn't need to know any contract addresses. Also, Aquarius no longer needs an Azure account account name, account key or container name.

Removed all mentions of keepers, Ganache and Azure

---

setup.py

so this pull request removes it from the `install_requirements`.

Aquarius doesn't need squid-py any more

---

docs/for_operators/README.md

For now, anyone setting up a marketplace should probably just use the Docker Compose setup that Pleuston devs use, to run Aquarius and several other components. That's all outlined on the docs page about setting up a marketplace, so I linked there.

Point would-be Aquarius operators to the docs site

---

Makefile
setup.cfg
setup.py
tox.ini

We use Codacy (which uses PyLint) to check Python code style, not Flake8 or pyflakes, so I removed all the Flake8 and pyflakes stuff. I also changed `make lint` to use PyLint instead of Flake8.

Cleanup Flake8

---

.bumpversion.cfg
aquarius/__init__.py
setup.cfg

This PR is the Aquarius analogue of https://github.com/oceanprotocol/brizo/pull/50 ... see the comments I made there to understand it.
Note that in Aquarius, the `__init__.py` file isn't empty, but it also wasn't getting updated because a `.bumpversion.cfg` file existed, so `setup.cfg` was being ignored by the bumpversion script.

Consolidate bumpversion config in .bumpversion.cfg

---

Dockerfile

In the `Dockerfile`, I changed `pip install -e .` (where `.` means the current directory) to get rid of the `-e` because that option is only if you want to keep pip re-installing from the local code (in `.`) every time the local code changes.
More info: https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs

Dockerfile shouldn't install Aquarius in editable mode

---

Dockerfile
config.ini
config.ini.template

The BigchainDB Testnet used to require an app_id and app_key in the HTTP request header, but it doesn't anymore, so we can remove all mentions of those.
I will do a similar pull request in https://github.com/oceanprotocol/oceandb-bigchaindb-driver

Remove all mentions of BDB app_id and app_key

---

setup.py

I was getting an error when trying to install Aquarius from source and it turned out to be because of this typo.

Fixed a typo in setup.py

---

aquarius/app/assets.py
config.ini
tests/conftest.py

Check that there are no urls when you are trying to write in oceandb using aquarius. Update to OEP8.
https://github.com/oceanprotocol/ocean/issues/291

Check that there are not urls in the files

---

aquarius/events/metadata_updater.py

Sometime, we will get multiple events => same pool.  Let's filter that, in order to avoid structure like this:
"price": {
"datatoken": 489.7318486533372,
"ocean": 560282.3065683485,
"value": 503.6179181382843,
"type": "pool",
"address": "0xAAB9EaBa1AA2653c1Dda9846334700b9F5e14E44",
"pools": [
"0xAAB9EaBa1AA2653c1Dda9846334700b9F5e14E44",
"0xAAB9EaBa1AA2653c1Dda9846334700b9F5e14E44",
"0xAAB9EaBa1AA2653c1Dda9846334700b9F5e14E44",
"0xAAB9EaBa1AA2653c1Dda9846334700b9F5e14E44",
"0xAAB9EaBa1AA2653c1Dda9846334700b9F5e14E44",
"0xAAB9EaBa1AA2653c1Dda9846334700b9F5e14E44",
"0xAAB9EaBa1AA2653c1Dda9846334700b9F5e14E44",
"0xAAB9EaBa1AA2653c1Dda9846334700b9F5e14E44",
"0xa81798FEc662C1A131029B28546Cc80ECd11CB61"
],
"isConsumable": "true"

filter multiple pools

---

bumpversion.sh

Removes mentions of master branch in code (only found in bumpversion.sh)
Closes #385.

Remove references to master in bumpversion.sh.

---

aquarius/app/assets.py
aquarius/app/dao.py

Treat ElasticSearch NotFoundExceptions in get by did endpoint as misses, not errors. Remove overzealous logging and make these an informative log.
Closes #414.

Tones down asset not found errors.

---

aquarius/events/events_monitor.py
aquarius/events/metadata_updater.py

Aquarius issue #388 requested removing price.address and replacing it with price.exchange_id. However price.address is needed for pools. It was added back in for the appropriate cases.
- [x ] Bug fix (non-breaking change which fixes an issue)

Add price.adddress again for pools

---

aquarius/events/metadata_updater.py

This PR simply fixes a couple of log statements that were not updated when the `exchange_id` logic changed in #424. The erroneous logs were discovered while investigating #410. 
Closes #435 
Cleanup for #424

Fix log statements related to price.exchange_id

---

README.md

Fixes #519 
Changes:
* Add python3-dev and wheel to the install instructions
Test:
<details>
<summary>Console log of successful install</summary>
<p>
```console
david@david-Inspiron-5502:~/projects/aquarius$ apt list --installed python3-dev
Listing... Done
david@david-Inspiron-5502:~/projects/aquarius$ sudo apt install python3-dev
[sudo] password for david: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
libexpat1-dev libpython3-dev libpython3.8-dev python3.8-dev
The following NEW packages will be installed:
libexpat1-dev libpython3-dev libpython3.8-dev python3-dev python3.8-dev
0 upgraded, 5 newly installed, 0 to remove and 116 not upgraded.
Need to get 4,577 kB of archives.
After this …
```

Add python3-dev and wheel to install instructions (#519)

---

.bumpversion.cfg
aquarius/__init__.py
setup.py

Since we broke endpoints, we should release a new minor version, and not just a patch increment.

Bump version: 3.0.2 → 3.1.0

---

.bumpversion.cfg
aquarius/__init__.py
setup.py

Update ocean-contracts dependency

---

aquarius/events/processors.py
aquarius/events/purgatory.py
tests/test_purgatory.py

Fixes #621 .
- Move IsPurgatory field to stats field in ddo aqua asset
- Update tests

Move isPurgatory field to stats field in aqua ddo asset

---

aquarius/events/processors.py
tests/helpers.py
tests/test_assets_api.py
tests/test_events.py

Service ids

---

aquarius/events/processors.py
tests/test_events.py

Fixes issue #632 .
Changes proposed in this PR:
- Update NTF state field in ES when a `MetadaState` event is received and the state is other than active

Update NFT state field in ES when MetadaState event received

---

tests/test_events.py

Signed-off-by: Pablo Maldonado <pablo@oceanprotocol.com>
Description:
- Fix github actions tests by delaying MetadataState updates between them
Related to Issue #632

Space MetadaState events updates in events tests

---

aquarius/events/util.py
setup.py

- syncs up the package upgrades from main
- upgrades web3 package and fixes the new fee issue with buildTransaction: https://stackoverflow.com/questions/70051896/python-web3-and-ganache-error-method-eth-maxpriorityfeepergas-not-supported. [supersedes https://github.com/oceanprotocol/aquarius/pull/630]
- minor cosmetic improvement of the metadata start block TODO

Mirror setup.py updates from main.

---

aquarius/events/decryptor.py

This change is based on the `decrypt` endpoint unit tests in provider.
https://github.com/oceanprotocol/provider/blob/v4main/tests/test_encryption.py#L331-335
```python
nonce = str(datetime.now().timestamp())
message_to_be_signed = (
f"{set_metadata_tx_id}{decrypter_wallet.address}{chain_id}{nonce}"
)
signature = sign_message(message_to_be_signed, decrypter_wallet)
```

Make nonce a str

---

aquarius/events/decryptor.py
aquarius/events/processors.py
tests/test_ddo_checker_shacl.py
tests/test_events.py
tests/test_processors.py
tests/test_validate_api.py

Fixes:
- remove hash based on json, use provider response  (Reason:  JSON.dumps in python is different than json.stringify in nodejs  -> assets published using ocean.js were failing the hash check)
- make sure we output an error when PRIVATE_KEY is not defined
- moved all token name, symbol, etc getters to functions so we can log them and ignore failures
- remove old public key check  (the owner is the nft, all logic is in the smartcontract, so he can update the ddo using any params, maybe he is changing owners)

improvements

---

aquarius/ddo_checker/shacl_schemas/v4/remote_4.0.0.ttl

Due to https://github.com/oceanprotocol/multi-repo-issue/issues/127, there is no need to store compute related fields in the ddo (like cpu, namespace, volume size, etc).
Once this is merged, I will remove them from V4 DDO docs as well

remove cpu, gpu, etc from required

---

aquarius/events/util.py

Signed-off-by: Pablo Maldonado <pablo@oceanprotocol.com>
Fixes #708 .
- Add mumbai to the `geth_poa_middleware` config

Fix extraData size error in mumbai network

---

aquarius/app/assets.py
aquarius/events/events_monitor.py
aquarius/events/processors.py
aquarius/events/util.py
tests/helpers.py

Closes #721.
Changes:
- Eliminate MismatchedABI warnings by adding `errors=DISCARD` argument to all `processReceipt() calls.

Eliminate MismatchedABI warnings

---

aquarius/app/assets.py
aquarius/app/util.py
aquarius/events/processors.py
aquarius/rbac.py
aquarius/run.py
tests/test_util.py

Adds RBAC filtering

---

aquarius/events/processors.py
tests/test_events.py

When processing EVENT_METADATA_STATE, if previous nft state are not active, allow to change to the new nft state.
Related to Issue #836

Restore nft state during EVENT_METADATA_STATE processing

---

README.md

Closes #811. I've not moved the entire text because I don't want to suffocate this main readme, which is already long enough.

Add instructions on running Aquarius locally.

---

aquarius/app/es_mapping.py
aquarius/events/constants.py
aquarius/events/events_monitor.py
aquarius/events/processors.py
aquarius/events/util.py
aquarius/graphql.py
tests/test_events.py
tests/test_graphql.py
tests/test_processors.py

Update price and change orderCount calcs.

---

API.md
aquarius/config.py
aquarius/events/events_monitor.py
aquarius/run.py
tests/test_events.py

When running Aquarius with multiple event monitors, it's hard to detect what version is used.
Export events monitor version in ["/api/aquarius/chains/status/{chain_id}"](https://github.com/oceanprotocol/aquarius/blob/main/API.md#get-apiaquariuschainsstatuschain_id)
This PR is toward functionality, because performance wise, it's not the best idea to always update es and keep the same value (version)

export event version

---

API.md
aquarius/app/assets.py
aquarius/app/chains.py
aquarius/events/events_monitor.py
aquarius/graphql.py
aquarius/retry_mechanism.py
tests/test_events.py
tests/test_retry_mechanism.py

Closes #936 
- refactor queue
- add queue handlers for tx/block/event
- add endpoint to fetch queue

new retry queue

---

API.md
aquarius/app/chains.py
aquarius/app/es_instance.py
aquarius/app/state.py
aquarius/app/util.py
aquarius/constants.py
aquarius/events/decryptor.py
aquarius/events/processors.py
aquarius/events/util.py
aquarius/run.py
tests/test_decryptor.py
tests/test_events.py

Closes #958 
A state object looks like:
```
obj = {
"nft": nft_address,
"did": did,
"chain_id": chain_id,
"tx_id": txid,
"valid": valid,
"error": error,
}
```
Intresting results:
1. Valid nft/ddo
```bash
curl http://172.15.0.5:5000/api/aquarius/state/ddo?did=did:op:9c1235050bcd51c8ec9a7058110102c9595136834911c315b4f739bc9a880b8e
```
```json
{"chain_id":5,"error":null,"nft":"0x3A695322d631451474090F322eA3d8d2eC8c1562","tx_id":"0x5f4b51adab1971c0c0479e275ed298670eb216d8fd87801c5fc03f34417754b3","valid":true}
```
2. Nft not deployed by our factory
```bash
curl http://172.15.0.5:5000/api/aquarius/state/ddo?nft=0xC7ED00725AAb7E679fCB46C9620115fE0B6dD94a
```
```json
{"chain_id":80001,"error":"nft not deployed by our factory","nft":"0xC7ED00725AAb7E679fCB46C9620115fE0B6dD94a","tx_id":"0xcd715efd2 …
```

add ddo states

---

aquarius/events/constants.py
aquarius/events/processors.py

When an asset is marked as EOL, it should be discoverable in OM, while ordering remains disabled

fix EOL state
