README.md

I went to install a local Provider today and found the `README.md` file a bit confusing so I edited it.
- made it more clear that the instructions there are for local dev and test (not production)
- changed the order of the instructions to the order that one would actually do
- added `pip install -r requirements_dev.txt`
That last point raised a question for me. I'm used to doing something like `pip install -e .[dev]` and having that install all the dev requirements. (To see one example, check out [BigchainDB's setup.py file](https://github.com/bigchaindb/bigchaindb/blob/master/setup.py).) Is the reason for this because Conda somehow needs a slightly-different set of Python packages?
Should we mention that there's a `requirements_conda.txt` for Conda users?
No.

Edited README.md for clarity & correctness

---

aquarius/app/assets.py
aquarius/app/dao.py
tests/conftest.py
tests/test_api.py

Update logic in aquarius API to support ddo.
#77

Update logic for support new data structure for ddos

---

aquarius/app/assets.py

Fix error in the update of the createDate field in the metadata.
No

Fix error in update of createDate

---

config.ini

Update collection and db names

---

aquarius/run.py
docs/API.md
requirements_dev.txt

Add API documentation.
https://github.com/oceanprotocol/ocean/issues/121

Add API documentation.

---

requirements_conda.txt
requirements_dev.txt

to 2.20.0 to address [CVE-2018-18074](https://nvd.nist.gov/vuln/detail/CVE-2018-18074).

Update the required version of the requests package

---

.bumpversion.cfg
setup.cfg
setup.py

Release version 0.1.2

---

.bumpversion.cfg
aquarius/app/assets.py
setup.cfg
setup.py
tests/test_api.py

Fix issue with the retunr of the text_search endpoint. The problem was using the jsonify librart of `flask` that was converting everything into a string.
https://github.com/oceanprotocol/pleuston/issues/168

Remove issue returning string instead of object

---

.bumpversion.cfg
setup.cfg
setup.py

Bumpversion for new release.

---

aquarius/constants.py
aquarius/run.py

Added swagger spec for documentation
No

added basePath for swagger

---

aquarius/constants.py
aquarius/run.py

Make swagger doc get rendered again.
Related to Issue #119

Make swagger doc work again

---

aquarius/app/assets.py
tests/test_api.py

Create a delete all endpoint to facilitate testing.
Related to Issue #85

Add delete all endpoint

---

setup.py

Try to fix a security issue in pyyaml upgrading the version.
No

Fix security issue in pyyaml

---

.bumpversion.cfg
aquarius/__init__.py
setup.py

bump version for stable release

Bump version: 0.1.4 → 0.1.5

---

.bumpversion.cfg
aquarius/__init__.py
setup.py

Bump version: 0.1.5 → 0.1.6

---

aquarius/app/assets.py
tests/conftest.py
tests/test_api.py

Require checksum field, and move the logic of the calculation to the different squid implementations.
No

Require checksum

---

.bumpversion.cfg
aquarius/__init__.py
setup.py

Bumpversion to 0.1.8 version including the checksum requirement.

Bump version: 0.1.7 → 0.1.8

---

Dockerfile
config.ini
config.ini.template
setup.py

Update configs to make able to use elastic in barge.
No

Update config and template

---

aquarius/app/assets.py
tests/conftest.py
tests/test_api.py

Require field `created` and check that is in a valid format.
Close #136

Require create field

---

config.ini.template

Remove values that were breaking the Docker image.
No

Remove values in the template

---

aquarius/app/assets.py

Fix format of dates to save in mongo.
No

Save dates in mongo with iso format

---

docs/for_api_users/API.md
setup.py
tests/conftest.py
tests/test_api.py

Use the new format for queries. Now the drivers manage the queries that you can send.
Related to Issue #140 #127

Aquarius using drivers with predifined queries

---

.bumpversion.cfg
aquarius/__init__.py
setup.py

Bump version: 0.1.9 → 0.1.10

---

aquarius/app/assets.py
config.ini
setup.py

Upgrade plecos

---

aquarius/app/assets.py
tests/conftest.py
tests/test_api.py

Fix issue in the registering of the asset cause because the curation dictionary wasn't created.
No

Fix issue in the registering of assets

---

.bumpversion.cfg
aquarius/__init__.py
setup.py

Bump version: 0.1.10 → 0.1.11

---

CHANGELOG.md
MANIFEST.in
setup.py

Add changelog
oceanprotocol/ocean#273

Add changelog file

---

.bumpversion.cfg
aquarius/__init__.py
aquarius/app/assets.py
aquarius/app/dao.py
config.ini
setup.py
tests/test_api.py

Add the pagination in the search queries.
Related to Issue #167

Add pagination in the search methods

---

.bumpversion.cfg
CHANGELOG.md
aquarius/__init__.py
aquarius/app/assets.py
setup.py
tests/test_api.py

Save price as an integer to be supported in mongo.
Related to Issue #182

Save price as string to allow big numbers in mongo

---

.bumpversion.cfg
CHANGELOG.md
aquarius/__init__.py
aquarius/app/assets.py
setup.py
tests/conftest.py

Convert type of the price in the conditions to fix issue storing in mongo.
Related to Issue #182

Manage price type in the conditions

---

.bumpversion.cfg
CHANGELOG.md
aquarius/__init__.py
aquarius/app/assets.py
config.ini
setup.py
tests/test_api.py

Convert to int back when returning the content of the database until we update all the squids.

Sanitize the records to int back to work with the rest of the components

---

aquarius/app/assets.py
tests/conftest.py

Ensure "tags" is a list in all examples

---

aquarius/app/dao.py

Check if isLsted exist in the ddo.
Close #153

Check if isListed field exist

---

.bumpversion.cfg
CHANGELOG.md
aquarius/__init__.py
aquarius/app/assets.py
setup.py

Return list of error when some parameter is not valid.
No

Return the list of errors

---

Dockerfile
aquarius/app/assets.py
aquarius/config.py
config.ini
config.ini.template

Allow free assets only

---

.bumpversion.cfg
.travis.yml
CHANGELOG.md
aquarius/__init__.py
aquarius/app/assets.py
aquarius/config.py
aquarius/mapping.py
aquarius/run.py
config.ini
setup.py

Add mapping to elastic by default.
Small changes in the swagger doc to be accurated.

Add mapping by default in elastic

---

.bumpversion.cfg
CHANGELOG.md
aquarius/__init__.py
aquarius/run.py
setup.py
tests/test_api.py

Add health check endpoint

---

aquarius/app/assets.py

Applied format_timestamp() method, as described in open issue, to fix date formatting error.
Related to Issue #224

Apply format_timestamp() method on register()

---

Dockerfile
aquarius/app/assets.py
aquarius/app/util.py
tests/test_api.py
tox.ini

Allow rating_backend to update curation for a DID

allow curation update by rating_backend

---

aquarius/app/assets.py

Allow DELETE of a did, with a required signature if host != localhosy

allow delete

---

aquarius/app/assets.py
aquarius/app/util.py
tests/test_api.py
tox.ini

allow accessWhiteList and freeWhiteList

allow accessWhiteList and freeWhiteList

---

aquarius/app/assets.py
tests/ddos/ddo_sample_updates.py
tests/test_api.py

Part of https://github.com/oceanprotocol/ocean/issues/415

add compute privacy

---

.bumpversion.cfg
aquarius/__init__.py
aquarius/app/assets.py
aquarius/app/auth_util.py
aquarius/app/util.py
aquarius/events/events_monitor.py
aquarius/events/metadata_updater.py
setup.py

* improved text search
* sort search results by score/relevancy
* add endpoints for delisting an asset and for updating a single asset's price info

allow triggering update of a single asset.

---

.bumpversion.cfg
aquarius/__init__.py
setup.py

Bump version: 2.2.1 → 2.2.2

---

.bumpversion.cfg
aquarius/__init__.py
aquarius/app/assets.py
setup.py

Fix manual ddo pool update

---

aquarius/app/assets.py
tests/test_api.py

Adds an endpoint to validate remote DDOs.
Closes #364

Adds endpoint to validate remote DDO.

---

aquarius/app/assets.py

Allows update requests from 127.0.0.1
Related to Issue #363.

Allow update requests from 127.0.0.1.

---

.gitignore
aquarius/app/assets.py

Fixes the delist endpoint for metadata updating, which was missing a parameter.
Possibly closes #342, but it might be already fixed, let's see during the reviews.

Possibly fixes delist_ddo endpoint.

---

aquarius/events/metadata_updater.py

Reduce duplication in event monitor and add logging messages for price retrieval.
Related to Issue #361.
Possible improvement to logging. Improvement that reduces code duplication.

Removes some code duplication in price updating, adds logging.

---

README.md

Documentation: Fix typo

---

aquarius/app/assets.py
aquarius/app/util.py
aquarius/events/events_monitor.py
tests/test_api.py

- uses the POST method and endpoint "assets/names"
- expects "didList" in the requests payload 
- returns json object mapping did to name
- Changes the metadata endpoint to return the metadata instead of the metadata-service
- this may impact the market

add endpoint to get assets names.

---

README.md
aquarius/block_utils.py
aquarius/events/events_monitor.py
aquarius/events/metadata_updater.py
tests/test_util.py

optionally ignore last block on resume

---

.bumpversion.cfg
aquarius/__init__.py
setup.py
tests/test_api.py

- fix test_encrypt_ddo to use new query type
- bump version
-

Feature/release 2.2.5

---

aquarius/app/assets.py

Take out query_string assertion on es search.

---

aquarius/app/dao.py

Are we supposed to default to first page? That seems right but I'm not sure. Right now we require a valid page parameter, but we could do with fallback when "page" and "offset" are empty.

To be discussed: Add default values in ES query.

---

aquarius/app/assets.py
aquarius/app/dao.py
aquarius/app/util.py
tests/test_api.py

Adds results metadata
Closes #223. Decided with @kremalicious that we'll only implement licenses for now, not categories.

Adds result metadata for licenses.

---

aquarius/events/metadata_updater.py

Closes "Aquarius should process ExchangeRateChanged events as well", but without unit tests

fix fre price update

---

.bumpversion.cfg
aquarius/__init__.py
setup.py

release 2.2.7

---

aquarius/events/events_monitor.py

Process blocks in 1000 block chunks when syncing Aquarius with the current block.
Closes #448

Process blocks in 1000 block chunks

---

aquarius/events/util.py
setup.py

Towards https://github.com/oceanprotocol/ocean.py/issues/304

Replace Web3Helper with module functions from utils

---

aquarius/app/assets.py
aquarius/events/datatoken_abi.json
aquarius/events/processors.py
aquarius/events/util.py
setup.py
tests/conftest.py
tests/helpers.py

Stable aqua remove py

---

aquarius/app/assets.py
aquarius/events/events_monitor.py

add debug statements

---

README.md
aquarius/app/assets.py
aquarius/app/auth_util.py
aquarius/app/util.py
aquarius/events/decryptor.py
aquarius/events/events_monitor.py
aquarius/events/processors.py
aquarius/events/request.py
aquarius/events/util.py
deployment/README.md
deployment/aquarius-standard-networks-deployment-example.yaml
setup.py
tests/helpers.py
tests/test_api.py
tests/test_events.py

- Add debug statements from #476

Stable aqua cleanup

---

aquarius/app/dao.py

Implicit sorting

---

.github/workflows/tox.yml
README.md
aquarius/events/processors.py
aquarius/events/purgatory.py
tests/test_events.py

Adds RBAC permissions to Aquarius.

---

aquarius/app/assets.py
tests/test_api.py

Adds direct interrogation to ES.

---

README.md
aquarius/app/assets.py
aquarius/app/dao.py
aquarius/app/util.py
tests/test_api.py

Remove results metadata

---

.bumpversion.cfg
aquarius/__init__.py
setup.py

Bump version: 2.2.12 → 3.0.0

---

RELEASE_PROCESS.md

Modify `RELEASE_PROCESS.md` file and make it easy to follow steps.
Related to Issue #521

Make it easier to follow release process steps

---

aquarius/app/util.py
aquarius/block_utils.py
aquarius/config.py
aquarius/constants.py
aquarius/events/constants.py
aquarius/events/purgatory.py
aquarius/events/util.py
aquarius/myapp.py
aquarius/run.py

Based on #518.
Related to Issue #517.

Add docstrings (rebased)

---

aquarius/ddo_checker/schemas/metadata_local_v0_6.json
tests/test_api.py

Related to https://github.com/oceanprotocol/multi-repo-issue/issues/98

Credentials validation.

---

.bumpversion.cfg
aquarius/__init__.py
aquarius/events/processors.py
setup.py

fix rbac address

---

aquarius/events/processors.py
developers.md

Add instructions for running ES from Docker

---

README.md
aquarius/constants.py
tests/test_assets_api.py
tests/test_es_exceptions.py

Closes #547.
Changes proposed in this PR:
- Removed v1 from the base endpoint

Remove v1 from the base endpoint

---

aquarius/events/processors.py
aquarius/events/purgatory.py
tests/test_purgatory.py

Purgatory updates

---

aquarius/events/processors.py
aquarius/events/purgatory.py
tests/test_purgatory.py

Signed-off-by: Pablo Maldonado <pablo@oceanprotocol.com>
Fixes #675 .
Update `ddo.purgatory.state` type to boolean

Update purgatory state type

---

aquarius/app/assets.py
aquarius/app/es_mapping.py

Done, but waiting for other repos to sync the change.
Closes #668

Adapt datatoken language.

---

.github/workflows/pytest.yml

add docker check

---

aquarius/events/util.py
setup.py
tests/test_events.py

Closes #701 
Update to contracts v1.0.0-alpha.19

bump contracts to v1.0.0-alpha.19

---

setup.py

Contracts update to v1.0.0-alpha.20

---

.gitignore
API.md
README.md

Create a new API.md file.
Related to Issue #703

Create API.md file

---

API.md
aquarius/app/assets.py
aquarius/app/util.py
aquarius/events/events_monitor.py
tests/test_events.py

Trigger caching

---

.codeclimate.yml
aquarius/events/events_monitor.py
pytest.ini
start_elasticsearch.sh
tests/test_events.py

Fixes #710 
Changes:
- Replace event filtering with a loop that searches through chunks of 1000 blocks, starting from the lowest block number

Issue710 replace event filtering

---

aquarius/ddo_checker/shacl_schemas/v4/remote_4.0.0.ttl

Additional information

---

aquarius/events/decryptor.py
aquarius/events/processors.py

Added logs for decrypt DDO event.
Related to Issue #723

Added logs for decrypt DDO event.

---

.github/workflows/pytest.yml
setup.py

bump contracts to alpha22

---

aquarius/events/decryptor.py
tests/test_decryptor.py

Experimental decode.

---

.bumpversion.cfg
README.md
aquarius/__init__.py
aquarius/events/events_monitor.py
aquarius/events/util.py
setup.py
tests/test_events.py

Take BFACTORY BLOCK into account.

---

aquarius/ddo_checker/shacl_schemas/v4/remote_4.0.0.ttl

Adds multiline descriptions.

---

aquarius/events/processors.py
tests/test_events.py

Work on https://github.com/oceanprotocol/multi-repo-issue/issues/143

Adjust MetadataState treatment

---

aquarius/app/assets.py
tests/test_validate_api.py

Adds RBAC validation.

---

.bumpversion.cfg
aquarius/__init__.py
aquarius/events/events_monitor.py
aquarius/events/processors.py
aquarius/graphql.py
setup.py

Add more logs to order started.

---

.bumpversion.cfg
.github/workflows/pytest.yml
aquarius/__init__.py
aquarius/events/util.py
aquarius/graphql.py
setup.py

Bump contracts to 1.0.0a28

---

.bumpversion.cfg
.github/workflows/pytest.yml
aquarius/__init__.py
aquarius/app/util.py
aquarius/events/decryptor.py
setup.py

refactor signatures

---

.github/workflows/tox.yml
aquarius/events/events_monitor.py
aquarius/events/util.py
setup.py
tests/test_events.py

Fixes #710 
Changes:
- Replace event filtering
- Fix bug where CI was using v4 barge instead of v3 barge.
- Add instruction to print contents of `address.json` in CI logs
- Bump flask from 2.0.2 to 2.1.2

Issue710 replace event filtering v3

---

.bumpversion.cfg
aquarius/__init__.py
setup.py

bump contracts to alpha 33

---

.bumpversion.cfg
aquarius/__init__.py
setup.py

bump to contracts 34

---

aquarius/app/assets.py
aquarius/app/chains.py
aquarius/app/util.py
aquarius/events/processors.py
aquarius/rbac.py
tests/test_assets_api.py
tests/test_util.py

Add json content type on requests

---

aquarius/run.py
developers.md

Create a command to force set last processed block.

---

aquarius/events/purgatory.py

Fix empty reason in purgatory.

---

API.md
README.md

Fix broken doc links in the README

Fix broken links in the README

---

aquarius/events/decryptor.py
aquarius/events/processors.py
aquarius/retry_mechanism.py
tests/test_events.py
tests/test_processors.py

Fix retry queue

---

aquarius/events/events_monitor.py

Dynamic blocks

---

.bumpversion.cfg
aquarius/__init__.py
aquarius/events/events_monitor.py
setup.py

Closes #923 
Move queue process out of process_current_blocks
And have an error handle for that

move queue process out of process_current_blocks

---

aquarius/events/ve_allocate.py

use ve_allocate_realtime instead of ve_allocate

---

aquarius/app/es_instance.py
aquarius/events/decryptor.py
aquarius/events/nft_ownership.py
aquarius/events/processors.py
aquarius/graphql.py

Fix multiple issues (#932 , #924 , #933)

---

aquarius/ddo_checker/shacl_schemas/v4/remote_4.5.0.ttl

Adding minimum lengths for containerShape fields

add minLenghts

---

.bumpversion.cfg
.github/workflows/pytest.yml
aquarius/__init__.py
setup.py

Use main barge, since we have merged https://github.com/oceanprotocol/barge/pull/340

Use main barge

---

aquarius/app/assets.py
aquarius/run.py

Add logIndex to triggerCaching.

---

aquarius/events/util.py

Make PUBLIC_RPC optional

---

.bumpversion.cfg
aquarius/__init__.py
setup.py

Bump version 5.1.4 -> 5.1.5

---

Dockerfile

Optimize Dockerfile for further deployments.
Related to Issue #1055

Optimize Dockerfile.

---

.bumpversion.cfg
aquarius/__init__.py
setup.py

Bump version to v5.1.5 -> v5.1.6

---

.bumpversion.cfg
.github/workflows/pytest.yml
aquarius/__init__.py
setup.py
tests/test_events.py

bump contracts

---

.bumpversion.cfg
aquarius/__init__.py
aquarius/events/purgatory.py
pytest.ini
setup.py
tests/test_purgatory.py

Filtering accounts purgatory
Related to Issue #1040

Filtering accounts purgatory
